spring:
  datasource:
    url: jdbc:mysql://${db-config.host}:${db-config.port}/${db-config.database}?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${db-config.username}
    password: ${db-config.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#logging:
#  level:
#    root: debug
#

### Swagger ###
springdoc:
  packages-to-scan: com.heeda.swagger
  api-docs:
    path: /v3/api-docs  # API Docs 경로
  swagger-ui:
    path: /api-docs/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
